name: Build runtime
on:
  push:
  pull_request:
jobs:
  build_fw:
    name: "Build runtime"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install ESP-IDF
        uses: ./.github/actions/setup-esp-idf
        with:
          version: v4.3
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            python-yaml # For Duktape configuration
      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          cd runtime
          cp main/credentials_template.hpp main/credentials.hpp
          idf.py build
          idf.py size
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: sudo apt install doxygen
      - run: pip install mkdocs-material
      - run: pip install mkdocs-doxygen-snippets-plugin
      - run: pip install mkdocs-awesome-pages-plugin

      - run: mkdocs gh-deploy --force



